CREATE OR REPLACE SYNONYM CONSOLE_CAT_USER FOR INTFMW_ADM.CONSOLE_CAT_USER;
CREATE OR REPLACE SYNONYM CONSOLE_CAT_PROFILE FOR INTFMW_ADM.CONSOLE_CAT_PROFILE;
CREATE OR REPLACE SYNONYM CONSOLE_CAT_MENU_ITEM FOR INTFMW_ADM.CONSOLE_CAT_MENU_ITEM;
CREATE OR REPLACE SYNONYM CONSOLE_PROFILE_MENU FOR INTFMW_ADM.CONSOLE_PROFILE_MENU;