# config context path to "/" by setting an empty string
server:
  contextPath:

# JACKSON
spring:
  jackson:
    serialization:
      INDENT_OUTPUT: true

  logging:
    level:
      org.springframework:
          web: WARN
          security: WARN
      org.hibernate: ERROR

route:
    authentication:
      path: auth
jwt:
  header: Authorization
  secret: mySecret
  expiration: 604800
  route:
    authentication:
      path: auth
      refresh: refresh

auth:
  endpoint: http://172.21.21.21:11006/izzi-ldap-auth/auth
  message:
    token: Authentication token is missing or invalid
#logging:
#  level:
#    org.springframework:
#      security: DEBUG
